<?php
/**
 * Load the function wrappers generated by the isolated Safe dependency.
 *
 * Mozart prefixes the functions, but Composer cannot discover functions through
 * PSR-4. Keep their eager-loading behavior without exposing the global Safe
 * namespace to other WordPress plugins.
 *
 * @package WP_Defender
 */

$safe_base_directory = __DIR__ . '/packages/Safe';
$safe_deprecated     = glob( $safe_base_directory . '/deprecated/*.php' );
$safe_generated      = glob( $safe_base_directory . '/generated/*.php' );
$safe_files          = array_merge(
	false === $safe_deprecated ? array() : $safe_deprecated,
	false === $safe_generated ? array() : $safe_generated,
	array( $safe_base_directory . '/lib/special_cases.php' )
);

foreach ( $safe_files as $safe_file ) {
	if ( 'functionsList.php' !== basename( $safe_file ) && is_file( $safe_file ) ) {
		require_once $safe_file;
	}
}

unset( $safe_base_directory, $safe_deprecated, $safe_generated, $safe_files, $safe_file );
