/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubscriptionsImport } from './routes/subscriptions'
import { Route as StoryImport } from './routes/story'
import { Route as StatisticsImport } from './routes/statistics'
import { Route as SourcesImport } from './routes/sources'
import { Route as SettingsImport } from './routes/settings'
import { Route as SalesImport } from './routes/sales'
import { Route as ReportingImport } from './routes/reporting'
import { Route as EngagementImport } from './routes/engagement'
import { Route as IndexImport } from './routes/index'
import { Route as TableVariantImport } from './routes/table.$variant'
import { Route as SettingsSettingsIdImport } from './routes/settings.$settingsId'
import { Route as ReportingReportingIdImport } from './routes/reporting.$reportingId'

// Create/Update Routes

const SubscriptionsRoute = SubscriptionsImport.update({
  path: '/subscriptions',
  getParentRoute: () => rootRoute,
} as any)

const StoryRoute = StoryImport.update({
  path: '/story',
  getParentRoute: () => rootRoute,
} as any)

const StatisticsRoute = StatisticsImport.update({
  path: '/statistics',
  getParentRoute: () => rootRoute,
} as any)

const SourcesRoute = SourcesImport.update({
  path: '/sources',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SalesRoute = SalesImport.update({
  path: '/sales',
  getParentRoute: () => rootRoute,
} as any)

const ReportingRoute = ReportingImport.update({
  path: '/reporting',
  getParentRoute: () => rootRoute,
} as any)

const EngagementRoute = EngagementImport.update({
  path: '/engagement',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TableVariantRoute = TableVariantImport.update({
  path: '/table/$variant',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSettingsIdRoute = SettingsSettingsIdImport.update({
  path: '/$settingsId',
  getParentRoute: () => SettingsRoute,
} as any)

const ReportingReportingIdRoute = ReportingReportingIdImport.update({
  path: '/$reportingId',
  getParentRoute: () => ReportingRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementImport
      parentRoute: typeof rootRoute
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingImport
      parentRoute: typeof rootRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesImport
      parentRoute: typeof rootRoute
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsImport
      parentRoute: typeof rootRoute
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryImport
      parentRoute: typeof rootRoute
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsImport
      parentRoute: typeof rootRoute
    }
    '/reporting/$reportingId': {
      id: '/reporting/$reportingId'
      path: '/$reportingId'
      fullPath: '/reporting/$reportingId'
      preLoaderRoute: typeof ReportingReportingIdImport
      parentRoute: typeof ReportingImport
    }
    '/settings/$settingsId': {
      id: '/settings/$settingsId'
      path: '/$settingsId'
      fullPath: '/settings/$settingsId'
      preLoaderRoute: typeof SettingsSettingsIdImport
      parentRoute: typeof SettingsImport
    }
    '/table/$variant': {
      id: '/table/$variant'
      path: '/table/$variant'
      fullPath: '/table/$variant'
      preLoaderRoute: typeof TableVariantImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ReportingRouteChildren {
  ReportingReportingIdRoute: typeof ReportingReportingIdRoute
}

const ReportingRouteChildren: ReportingRouteChildren = {
  ReportingReportingIdRoute: ReportingReportingIdRoute,
}

const ReportingRouteWithChildren = ReportingRoute._addFileChildren(
  ReportingRouteChildren,
)

interface SettingsRouteChildren {
  SettingsSettingsIdRoute: typeof SettingsSettingsIdRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsIdRoute: SettingsSettingsIdRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engagement': typeof EngagementRoute
  '/reporting': typeof ReportingRouteWithChildren
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sources': typeof SourcesRoute
  '/statistics': typeof StatisticsRoute
  '/story': typeof StoryRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/reporting/$reportingId': typeof ReportingReportingIdRoute
  '/settings/$settingsId': typeof SettingsSettingsIdRoute
  '/table/$variant': typeof TableVariantRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engagement': typeof EngagementRoute
  '/reporting': typeof ReportingRouteWithChildren
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sources': typeof SourcesRoute
  '/statistics': typeof StatisticsRoute
  '/story': typeof StoryRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/reporting/$reportingId': typeof ReportingReportingIdRoute
  '/settings/$settingsId': typeof SettingsSettingsIdRoute
  '/table/$variant': typeof TableVariantRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/engagement': typeof EngagementRoute
  '/reporting': typeof ReportingRouteWithChildren
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sources': typeof SourcesRoute
  '/statistics': typeof StatisticsRoute
  '/story': typeof StoryRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/reporting/$reportingId': typeof ReportingReportingIdRoute
  '/settings/$settingsId': typeof SettingsSettingsIdRoute
  '/table/$variant': typeof TableVariantRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engagement'
    | '/reporting'
    | '/sales'
    | '/settings'
    | '/sources'
    | '/statistics'
    | '/story'
    | '/subscriptions'
    | '/reporting/$reportingId'
    | '/settings/$settingsId'
    | '/table/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engagement'
    | '/reporting'
    | '/sales'
    | '/settings'
    | '/sources'
    | '/statistics'
    | '/story'
    | '/subscriptions'
    | '/reporting/$reportingId'
    | '/settings/$settingsId'
    | '/table/$variant'
  id:
    | '__root__'
    | '/'
    | '/engagement'
    | '/reporting'
    | '/sales'
    | '/settings'
    | '/sources'
    | '/statistics'
    | '/story'
    | '/subscriptions'
    | '/reporting/$reportingId'
    | '/settings/$settingsId'
    | '/table/$variant'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngagementRoute: typeof EngagementRoute
  ReportingRoute: typeof ReportingRouteWithChildren
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SourcesRoute: typeof SourcesRoute
  StatisticsRoute: typeof StatisticsRoute
  StoryRoute: typeof StoryRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TableVariantRoute: typeof TableVariantRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngagementRoute: EngagementRoute,
  ReportingRoute: ReportingRouteWithChildren,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SourcesRoute: SourcesRoute,
  StatisticsRoute: StatisticsRoute,
  StoryRoute: StoryRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TableVariantRoute: TableVariantRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/engagement",
        "/reporting",
        "/sales",
        "/settings",
        "/sources",
        "/statistics",
        "/story",
        "/subscriptions",
        "/table/$variant"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/engagement": {
      "filePath": "engagement.jsx"
    },
    "/reporting": {
      "filePath": "reporting.jsx",
      "children": [
        "/reporting/$reportingId"
      ]
    },
    "/sales": {
      "filePath": "sales.jsx"
    },
    "/settings": {
      "filePath": "settings.jsx",
      "children": [
        "/settings/$settingsId"
      ]
    },
    "/sources": {
      "filePath": "sources.jsx"
    },
    "/statistics": {
      "filePath": "statistics.jsx"
    },
    "/story": {
      "filePath": "story.jsx"
    },
    "/subscriptions": {
      "filePath": "subscriptions.jsx"
    },
    "/reporting/$reportingId": {
      "filePath": "reporting.$reportingId.jsx",
      "parent": "/reporting"
    },
    "/settings/$settingsId": {
      "filePath": "settings.$settingsId.jsx",
      "parent": "/settings"
    },
    "/table/$variant": {
      "filePath": "table.$variant.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
